import { safeJson } from "./domain-helpers.js";
import type { PreviewBridgeConfig } from "./preview-contract.js";

/**
 * The script that lives inside the preview document.
 *
 * It is the only piece of behaviour the preview carries, and it exists solely under
 * `options.preview` — the exported file never contains it. Its job is narrow on purpose:
 *
 *  - validate an incoming update completely before touching a single node,
 *  - commit all operations together or roll every one of them back,
 *  - keep focus, text selection and scroll position across a region replacement,
 *  - report clicks back as "open this editor field", and swallow real navigation.
 *
 * Trust model: the parent window reference plus the per-render `instanceId` are the capability.
 * The editor cannot address this document by origin (sandboxed srcdoc means an opaque origin), so
 * the incoming check is `event.source === parent` AND a strict origin equality whenever the editor
 * has a real origin AND the instance id. Outgoing messages always name the editor origin exactly.
 *
 * What the region check inside `parseRegion` is and is not: rejecting a `<script>` in incoming markup
 * is a guard against an accident — a renderer change that starts emitting a script into a region —
 * and NOT a sanitiser. It does not stop `<img onerror=…>`, inline handlers or anything else, and it
 * is not meant to: the markup comes from the editor's own buildWebsiteHtml, in the same tab, and
 * anyone able to put attacker markup into this message can already run code in the editor itself.
 * Should a region ever carry third-party markup, this needs a real sanitiser instead of this check.
 */
export function buildPreviewBridgeScript(config: PreviewBridgeConfig): string {
  const serialized = safeJson(config);
  return `<script>(()=>{
const c=${serialized};let currentRevision=c.revision;let applyingUpdate=false;let updateSequence=0;
const send=(action,payload={})=>parent.postMessage({channel:c.channel,version:c.version,instanceId:c.instanceId,renderGeneration:c.renderGeneration,revision:currentRevision,action,...payload},c.parentOrigin);
const fail=(reason)=>{const error=new Error(reason);error.previewReason=reason;throw error};
const targetKey=(target)=>JSON.stringify(target);
const exactTargets=(target,occurrence)=>[...document.querySelectorAll('[data-preview-target]')].filter((element)=>element.getAttribute('data-preview-target')===targetKey(target)&&(occurrence===undefined||element.getAttribute('data-preview-occurrence')===occurrence));
const regionElements=(region)=>[...document.querySelectorAll('[data-preview-region]')].filter((element)=>element.getAttribute('data-preview-region')===region);
// The 'script' check is an accident guard, not a sanitiser — see the trust-model note above.
const parseRegion=(operation)=>{const template=document.createElement('template');template.innerHTML=operation.html.trim();if(template.content.childElementCount!==1)fail('invalid-region');const root=template.content.firstElementChild;if(!root||root.getAttribute('data-preview-region')!==operation.region||root.querySelector('script'))fail('invalid-region');return root};
const captureFocus=(root)=>{const active=document.activeElement;if(!(active instanceof HTMLElement)||!root.contains(active))return null;return{target:active.getAttribute('data-preview-target'),occurrence:active.getAttribute('data-preview-occurrence'),selectionStart:'selectionStart'in active?active.selectionStart:null,selectionEnd:'selectionEnd'in active?active.selectionEnd:null}};
// Parking focus on the new root needs a tabindex, but only for the moment of the focus() call: an
// element keeps focus after the attribute is gone. Removing it right away keeps the patched document
// byte-identical to a full render instead of leaving a stray attribute behind.
const restoreFocus=(root,focus)=>{if(!focus)return;let target=null;if(focus.target){const inside=[...root.querySelectorAll('[data-preview-target]')];target=inside.find((element)=>element.getAttribute('data-preview-target')===focus.target&&element.getAttribute('data-preview-occurrence')===focus.occurrence)||inside.find((element)=>element.getAttribute('data-preview-target')===focus.target)||null}if(!(target instanceof HTMLElement)){root.setAttribute('tabindex','-1');root.focus({preventScroll:true});root.removeAttribute('tabindex');return}target.focus({preventScroll:true});if(typeof focus.selectionStart==='number'&&typeof focus.selectionEnd==='number'&&'setSelectionRange'in target){try{target.setSelectionRange(focus.selectionStart,focus.selectionEnd)}catch{}}};
const restoreViewport=(viewport)=>{if(scrollX===viewport.x&&scrollY===viewport.y)return;const root=document.documentElement,previous=root.style.scrollBehavior;root.style.scrollBehavior='auto';try{scrollTo(viewport.x,viewport.y)}finally{root.style.scrollBehavior=previous}};
const validate=(request)=>{if(request.baseRevision!==currentRevision)fail('revision-gap');if(request.revision<=currentRevision)fail('stale-revision');if(!Array.isArray(request.operations)||request.operations.length===0)fail('invalid-operation');const texts=[],regions=[],textKeys=new Set(),regionNames=new Set();let theme=null;for(const operation of request.operations){if(!operation||typeof operation!=='object'||typeof operation.type!=='string')fail('invalid-operation');if(operation.type==='patch-text'){if(typeof operation.value!=='string'||!operation.target||typeof operation.target!=='object'||operation.occurrence!==undefined&&typeof operation.occurrence!=='string')fail('invalid-operation');const key=targetKey(operation.target)+'|'+(operation.occurrence??'');if(textKeys.has(key))fail('conflicting-operations');textKeys.add(key);const matches=exactTargets(operation.target,operation.occurrence);if(matches.length===0)fail('unknown-target');if(matches.length!==1)fail('ambiguous-target');texts.push({element:matches[0],value:operation.value})}else if(operation.type==='replace-region'){if(typeof operation.region!=='string'||typeof operation.html!=='string'||regionNames.has(operation.region))fail('conflicting-operations');const current=regionElements(operation.region);if(current.length!==1)fail('invalid-region');regionNames.add(operation.region);regions.push({region:operation.region,current:current[0],next:parseRegion(operation)})}else if(operation.type==='patch-theme'){if(theme)fail('conflicting-operations');if(typeof operation.primary!=='string'||typeof operation.accent!=='string'||!/^#[0-9a-f]{6}$/i.test(operation.primary)||!/^#[0-9a-f]{6}$/i.test(operation.accent))fail('invalid-operation');theme={primary:operation.primary,accent:operation.accent}}else fail('invalid-operation')}for(const text of texts){const region=text.element.closest('[data-preview-region]');if(region&&regionNames.has(region.getAttribute('data-preview-region')))fail('conflicting-operations')}return{texts,regions,theme}};
const commit=(plan)=>{const viewport={x:scrollX,y:scrollY};const textRollback=plan.texts.map(({element})=>({element,value:element.textContent}));const regionRollback=[];const rootStyle=document.documentElement.style;const oldPrimary=rootStyle.getPropertyValue('--primary'),oldAccent=rootStyle.getPropertyValue('--accent');const meta=document.querySelector('meta[name="theme-color"]');const oldMeta=meta?meta.getAttribute('content'):null;try{for(const text of plan.texts)text.element.textContent=text.value;if(plan.theme){rootStyle.setProperty('--primary',plan.theme.primary);rootStyle.setProperty('--accent',plan.theme.accent);if(meta)meta.setAttribute('content',plan.theme.primary)}for(const replacement of plan.regions){const focus=captureFocus(replacement.current);replacement.current.replaceWith(replacement.next);regionRollback.push({old:replacement.current,next:replacement.next});restoreFocus(replacement.next,focus)}restoreViewport(viewport);return viewport}catch(error){for(const replacement of regionRollback.reverse()){if(replacement.next.isConnected)replacement.next.replaceWith(replacement.old)}for(const text of textRollback)text.element.textContent=text.value;rootStyle.setProperty('--primary',oldPrimary);rootStyle.setProperty('--accent',oldAccent);if(meta){if(oldMeta===null)meta.removeAttribute('content');else meta.setAttribute('content',oldMeta)}restoreViewport(viewport);throw error}};
addEventListener('message',(event)=>{if(event.source!==parent)return;if(c.parentOrigin!=='*'&&event.origin!==c.parentOrigin)return;const request=event.data;if(!request||request.channel!==c.channel||request.version!==c.version||request.instanceId!==c.instanceId||request.renderGeneration!==c.renderGeneration||request.action!=='apply-update'||typeof request.requestId!=='string'||!Number.isInteger(request.baseRevision)||!Number.isInteger(request.revision))return;try{const plan=validate(request);const sequence=++updateSequence;applyingUpdate=true;const viewport=commit(plan);currentRevision=request.revision;send('update-result',{requestId:request.requestId,success:true});requestAnimationFrame(()=>{if(sequence!==updateSequence)return;restoreViewport(viewport);applyingUpdate=false;reportScroll()})}catch(error){applyingUpdate=false;const reason=error&&typeof error==='object'&&typeof error.previewReason==='string'?error.previewReason:'internal-error';send('update-result',{requestId:request.requestId,revision:request.revision,success:false,reason})}});
const activateTarget=(editable,event)=>{event.preventDefault();event.stopPropagation();try{send('navigate-to-editor',{target:JSON.parse(editable.getAttribute('data-preview-target')||'')})}catch{}};
document.addEventListener('click',(event)=>{const target=event.target instanceof Element?event.target:null;const editable=target?target.closest('[data-preview-target]'):null;if(editable){activateTarget(editable,event);return}if(target&&target.closest('[data-preview-no-action]'))return;const link=target?target.closest('a'):null;if(link){const href=link.getAttribute('href')||'';event.preventDefault();event.stopPropagation();if(href.startsWith('#')&&href.length>1){const destination=document.querySelector(href);if(destination)requestAnimationFrame(()=>destination.scrollIntoView())}return}const button=target?target.closest('button'):null;if(button){event.preventDefault();event.stopPropagation();return}const section=target?target.closest('[data-preview-panel]'):null;if(section)send('navigate-to-editor',{target:{kind:'panel',panel:section.getAttribute('data-preview-panel')}})},true);
document.addEventListener('keydown',(event)=>{if(event.key==='Escape')return;const target=event.target instanceof Element?event.target.closest('[data-preview-target]'):null;if(!target||target.matches('a,button,input,select,textarea'))return;if(event.key==='Enter'||event.key===' ')activateTarget(target,event)},true);
let pendingScroll=false;const reportScroll=()=>{pendingScroll=false;if(applyingUpdate)return;const y=scrollY;const sections=[...document.querySelectorAll('[data-preview-section]')];const current=sections.findLast((element)=>element.offsetTop<=y+100)||sections[0];if(current)send('preview-scroll',{position:{section:current.getAttribute('data-preview-section')||'',offsetWithinSection:Math.max(0,y-current.offsetTop),fallbackScrollY:y}})};
addEventListener('scroll',()=>{if(applyingUpdate)return;if(!pendingScroll){pendingScroll=true;requestAnimationFrame(reportScroll)}},{passive:true});
addEventListener('load',()=>{const restore=c.restore;if(restore){const section=document.querySelector('[data-preview-section="'+CSS.escape(restore.section)+'"]');const y=section?section.offsetTop+restore.offsetWithinSection:restore.fallbackScrollY;restoreViewport({x:0,y:Math.max(0,Math.min(y,document.documentElement.scrollHeight-innerHeight))})}reportScroll();send('ready')})
})();</script>`;
}
